### PR TITLE
Replace package johnpbloch/wordpress with roots/wordpress.

### PR DESCRIPTION
**Pull request by strarsis**
(Announced in [this roots discourse discussion](https://discourse.roots.io/t/announcing-the-roots-wordpress-composer-package/14347?u=strarsis).)

### CODE REVIEW

**Comment by knowler** [comment]
Probably would be best to use the latest Bedrock as well, this repo isn't using the new `roots/wp-config` either.

**Comment by swalkinshaw** [comment]
We're going to re-do this all soon with Ubuntu 18.04 anyway

**Comment by knowler** [comment]
It would be great to automate it all too (pssst... @austinpray 😂)

**Comment by austinpray** [comment]
👁:nose::eye:

**Pull request closed without merging**
