### PR TITLE
Add brief Sage instructions to Readme

### PR DESCRIPTION
**Pull request by heyfletch**
If these minimum steps aren't done, Sage has no styling.

### CODE REVIEW

**Comment by retlehs** [comment]
i would rather reference https://github.com/roots/sage#theme-development or https://roots.io/sage/docs/theme-development/

**Comment by swalkinshaw** [comment]
Agreed with @retlehs.

Having this documentation here is just another place it can get out of sync :(

**Comment by heyfletch** [comment]
I agree there's potential it can get out of sync, but that's a small price to pay to make these instructions easier. There's already a lot of "go over there and read all those instructions and be sure you do everything correct and come back". 

If the point of this project is to get someone up and running with all 4 projects fairly quickly, then it's tough to be continually interrupted in the flow to go and read and understand all the various parts, and then still not be sure what needs to be done given all the other pieces of the puzzle. E.g., Ansible does a lot... will it run these build commands too? Since it's not clear, might as well make it explicit here. 

Those 3 build steps are necessary for Sage to work, so I think they need to be included here.

**Comment by heyfletch** [comment]
Updated the reference link per @retlehs

**Comment by swalkinshaw** [comment]
Good compromise :+1:

**Pull request merged**
